package io.moj.mobile.android.sdk;

/**
 * Created by skidson on 16-02-18.
 */
public class TestJson {

    public static final String CONDITION = "{\"Property\":\"property\",\"Position\":\"Above\",\"Max\":200.0,\"Min\":120.0,\"TimeProperty\":\"timeProperty\",\"Delay\":\"delay\",\"MinDataPoints\":4,\"Window\":\"window\"}";;
    public static final String TRANSPORT = "{\"TransportType\":\"HttpPost\",\"DeviceRegistrationId\":\"deviceRegistrationId\",\"DeviceToken\":\"deviceToken\",\"AppId\":\"appId\",\"AlertBody\":\"alertBody\",\"AlertSound\":\"alertSound\",\"AlertCategory\":\"alertCategory\",\"Badge\":3,\"Address\":\"address\",\"HostName\":\"hostName\",\"Topic\":\"topic\",\"Port\":1337,\"ConnectionString\":\"connectionString\",\"CollectionName\":\"collectionName\",\"Identifier\":\"Default\",\"HubName\":\"hubName\",\"Callback\":\"callback\",\"ClientId\":\"clientId\",\"UserName\":\"userName\",\"Password\":\"password\"}";
    public static final String OBSERVER = "{\"Key\":\"key\",\"CreatedOn\":\"createdOn\",\"LastModified\":\"lastModified\",\"ExpiryDate\":\"expiryDate\",\"Subject\":\"subject\",\"Type\":\"vehicle\",\"Fields\":[\"field1\",\"field2\"],\"Transport\":{\"TransportType\":\"HttpPost\",\"DeviceRegistrationId\":\"deviceRegistrationId\",\"DeviceToken\":\"deviceToken\",\"AppId\":\"appId\",\"AlertBody\":\"alertBody\",\"AlertSound\":\"alertSound\",\"AlertCategory\":\"alertCategory\",\"Badge\":3,\"Address\":\"address\",\"HostName\":\"hostName\",\"Topic\":\"topic\",\"Port\":1337,\"ConnectionString\":\"connectionString\",\"CollectionName\":\"collectionName\",\"Identifier\":\"Default\",\"HubName\":\"hubName\",\"Callback\":\"callback\",\"ClientId\":\"clientId\",\"UserName\":\"userName\",\"Password\":\"password\"},\"Transports\":[{\"TransportType\":\"HttpPost\",\"DeviceRegistrationId\":\"deviceRegistrationId\",\"DeviceToken\":\"deviceToken\",\"AppId\":\"appId\",\"AlertBody\":\"alertBody\",\"AlertSound\":\"alertSound\",\"AlertCategory\":\"alertCategory\",\"Badge\":3,\"Address\":\"address\",\"HostName\":\"hostName\",\"Topic\":\"topic\",\"Port\":1337,\"ConnectionString\":\"connectionString\",\"CollectionName\":\"collectionName\",\"Identifier\":\"Default\",\"HubName\":\"hubName\",\"Callback\":\"callback\",\"ClientId\":\"clientId\",\"UserName\":\"userName\",\"Password\":\"password\"}],\"Conditions\":{\"Debounce\":{\"Property\":\"property\",\"Position\":\"Above\",\"Max\":200.0,\"Min\":120.0,\"TimeProperty\":\"timeProperty\",\"Delay\":\"delay\",\"MinDataPoints\":4,\"Window\":\"window\"},\"Threshold\":{\"Property\":\"property\",\"Position\":\"Above\",\"Max\":200.0,\"Min\":120.0,\"TimeProperty\":\"timeProperty\",\"Delay\":\"delay\",\"MinDataPoints\":4,\"Window\":\"window\"},\"PropertyChanged\":{\"Property\":\"property\",\"Position\":\"Above\",\"Max\":200.0,\"Min\":120.0,\"TimeProperty\":\"timeProperty\",\"Delay\":\"delay\",\"MinDataPoints\":4,\"Window\":\"window\"},\"Throttle\":{\"Property\":\"property\",\"Position\":\"Above\",\"Max\":200.0,\"Min\":120.0,\"TimeProperty\":\"timeProperty\",\"Delay\":\"delay\",\"MinDataPoints\":4,\"Window\":\"window\"}}}";

}
